### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by luzemario**
pt-br version

### CODE REVIEW

**Comment by MefhigosetH** [comment]
Remember that all translation files must be in their proper language folder.

**Comment by luzemario** [comment]
I am using the "Edit this page" function in the main site... it is expected
to move the file to the right folder.


Em sáb, 18 de set de 2021 23:31, Victor Villarreal ***@***.***>
escreveu:

**Comment by MefhigosetH** [comment]
I understand @luzemario , but I was referring to the built-in i18n localization support of vuepress (the framework used to build the website). I have no time to document this feature, but I'll do soon.

Thanks for your continuos support on this project,

**Comment by luzemario** [comment]
Cool. Waiting for your time... :-)


Em seg, 20 de set de 2021 09:10, Victor Villarreal ***@***.***>
escreveu:

**Pull request merged**
